#+TITLE: User Interface Setup
#+OPTIONS: toc:nil ^:nil

From: https://github.com/flyingmachine/emacs-for-clojure/archive/book1.zip

These customizations change the way emacs looks and disable/enable
some user interface elements. Some useful customizations are
commented out, and begin with the line "CUSTOMIZE". These are more
a matter of preference and may require some fiddling to match your
preferences

* Show line numbers
#+BEGIN_SRC emacs-lisp
(global-linum-mode)
#+END_SRC


* Uncomment to hide tool bar and/or menu bar
#+BEGIN_SRC emacs-lisp
;; (when (fboundp 'tool-bar-mode)
;;   (tool-bar-mode -1))

;; (menu-bar-mode -1)
#+END_SRC


* Don't show native OS scroll bars for buffers because they're redundant
#+BEGIN_SRC emacs-lisp
  (when (fboundp 'scroll-bar-mode)
    (scroll-bar-mode -1))
#+END_SRC


* Make cursor blink
#+BEGIN_SRC emacs-lisp
  (blink-cursor-mode 1)
#+END_SRC



* Color Themes
Read http://batsov.com/articles/2012/02/19/color-theming-in-emacs-reloaded/
for a great explanation of emacs color themes.
https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html
for a more technical explanation.

Or simply use the build in leuven theme.
#+BEGIN_SRC emacs-lisp
  (load-theme 'leuven t)
#+END_SRC


* Increase font size for better readability
Uncomment the lines below by removing semicolons and play with the
values in order to set the width (in characters wide) and height
(in lines high) Emacs will have whenever you start it

#+BEGIN_SRC emacs-listp
  ;; (set-face-attribute 'default nil :height 140)
#+END_SRC

Better use 14 point PragmataPro
#+BEGIN_SRC emacs-lisp
(custom-set-faces
 '(default ((t (:family "PragmataPro" :foundry "unknown" :slant normal :weight normal :height 142 :width normal)))))

#+END_SRC


* Uncomment to control initial OS window size
#+BEGIN_SRC emacs-lisp
  ;; (setq initial-frame-alist '((top . 0) (left . 0) (width . 177) (height . 53)))
#+END_SRC


* Clipboard (copy, paste, kill, yank)
These settings relate to how emacs interacts with your operating system

#+BEGIN_SRC emacs-lisp
  (setq ;; makes killing/yanking interact with the clipboard
	x-select-enable-clipboard t

	;; I'm actually not sure what this does but it's recommended?
	x-select-enable-primary t

	;; Save clipboard strings into kill ring before replacing them.
	;; When one selects something in another program to paste it into Emacs,
	;; but kills something in Emacs before actually pasting it,
	;; this selection is gone unless this variable is non-nil
	save-interprogram-paste-before-kill t

	;; Shows all options when running apropos. For more info,
	;; https://www.gnu.org/software/emacs/manual/html_node/emacs/Apropos.html
	apropos-do-all t

	;; Mouse yank commands yank at point instead of at click.
	mouse-yank-at-point t)
#+END_SRC


* Misc
#+BEGIN_SRC emacs-lisp
  ;; full path in title bar
  (setq-default frame-title-format "%b (%f)")

  ;; don't pop up font menu
  (global-set-key (kbd "s-t") '(lambda () (interactive)))

  ;; no bell
  (setq ring-bell-function 'ignore)

#+END_SRC
